#########################################################################################
#        _____ _ _ _               _____                                                #
#       / ____(_) | |             / ____|                                     L I T E   #
#      | (___  _| | | ___   _    | (___  _ __   __ ___      ___ __   ___ _ __ ___       #
#       \___ \| | | |/ / | | |    \___ \| '_ \ / _` \ \ /\ / / '_ \ / _ \ '__/ __|      #
#       ____) | | |   <| |_| |    ____) | |_) | (_| |\ V  V /| | | |  __/ |  \__ \      #
#      |_____/|_|_|_|\_\\__, |   |_____/| .__/ \__,_| \_/\_/ |_| |_|\___|_|  |___/      #
#                        __/ |          | |                                             #
#                       |___/           |_|                                             #
#                                                                                       #
#########################################################################################
# By: BUTTERFIELD8 & The Zircon Network                                                 #
# Discord: https://discord.gg/7xfSC5p                                                   #
#########################################################################################

#Should a minded spawner drop to the ground or to the players inventory. [true=ground | false=inventory]
doDrop2Ground: true

#Anvil Rename - This will allow players to change the name of a Spawner
#Please note if 'true' players will be able to rename spawners and this can be used to scam them!
anvilRename: false

#Should players be able to mine spawners without the permission.
requireMineperm: true

#Drop Chance -> 0.00 = 0% | 1.00 = 100%
spawnerDropChance: 1.00

#Sets the cost of mining a spawner if enabled.
#PLEASE NOTE: This will require Vault to work!
chargeOnBreak:
  enabled: false
  price: 50.00
  sendMSG: true

#Blacklist worlds that you don't want player to be able to mine spawners.
#This would cause the spawner to break and drop xp for all worlds on the blacklist!
blacklist:
  - exampleworld
