#########################################################################################
#        _____ _ _ _               _____                                                #
#       / ____(_) | |             / ____|                                     L I T E   #
#      | (___  _| | | ___   _    | (___  _ __   __ ___      ___ __   ___ _ __ ___       #
#       \___ \| | | |/ / | | |    \___ \| '_ \ / _` \ \ /\ / / '_ \ / _ \ '__/ __|      #
#       ____) | | |   <| |_| |    ____) | |_) | (_| |\ V  V /| | | |  __/ |  \__ \      #
#      |_____/|_|_|_|\_\\__, |   |_____/| .__/ \__,_| \_/\_/ |_| |_|\___|_|  |___/      #
#                        __/ |          | |                                             #
#                       |___/           |_|                                             #
#                                                                                       #
#########################################################################################
# By: BUTTERFIELD8 & The Zircon Network                                                 #
# Discord: https://discord.gg/7xfSC5p                                                   #
#########################################################################################

#Should players be able to mine spawners without the permission.
requireMinePerm: false

#Should a minded spawner drop to the ground or to the players inventory. [true=ground | false=inventory]
doDrop2Ground: true

#Anvil Rename - This will allow players to change a spawners type by renaming it.
#Please note if 'false' you will not be able to rename spawners!
anvilRename: false

#Should players be able to mine spawners without the permission.
requireMineperm: true

#Drop Chance -> 0.00 = 0% | 1.00 = 100%
spawnerDropChance: 1.00